move build configuration into `pyproject.toml`
spacetelescope/stpipe pull request #56
Opened 2022-06-02 19:18 UTC by zacharyburnett

similar to https://github.com/spacetelescope/stcal/pull/95, since `setuptools` now supports `pyproject.toml` (albeit experimentally), we can move the build configuration from `setup.cfg[metadata]` to `pyproject.toml[project]`, and additionally use the `pyproject.toml[tool.setuptools]` table.

2022-09-20 15:07 UTC, WilliamJamieson requested changes

2022-09-20 15:07 UTC, WilliamJamieson commented on docs/source/conf.py
>  project = setup_metadata["name"]
```suggestion
project = setup_cfg["name"]
```

This should fix the failing Docs job. A bigger question is should we just create a RTD and have RTD build the docs?

2022-09-20 15:09 UTC, zacharyburnett commented
@WilliamJamieson I didn't realize that `stpipe` doesn't have a RTD site, I can make a PR to add that so we can get rid of the docs job in github actions

2022-09-20 15:22 UTC, WilliamJamieson requested changes

2022-09-20 15:22 UTC, WilliamJamieson commented on pyproject.toml
> +authors = [{ name = 'STScI' }]
```suggestion
authors = [{ name = 'STScI', email = 'help@stsci.edu' }]
```

There is no email, which is breaking the docs build

2022-12-15 14:19 UTC, WilliamJamieson approved these changes

2022-12-15 14:26 UTC, merged