test against pre-built binaries of `numpy`
spacetelescope/stpipe pull request #95
Opened 2023-05-09 13:30 UTC by zacharyburnett

This PR runs `devdeps` tests against the latest `pre` wheels of `astropy` and `numpy`

2023-05-09 20:39 UTC, WilliamJamieson requested changes

2023-05-09 20:39 UTC, WilliamJamieson commented on tox.ini
> +    devdeps: numpy>=0.0.dev0
See https://github.com/spacetelescope/romancal/pull/695#discussion_r1189076034 and https://github.com/spacetelescope/romancal/pull/695#discussion_r1189078751

2023-05-10 14:47 UTC, zacharyburnett commented
GitHub Actions are currently degraded; running `tox -e test-devdeps-xdist` locally results in the following `pip freeze`: 
```
asdf==2.15.0
asdf-standard==1.0.3
asdf-transform-schemas==0.3.0
asdf-unit-schemas==0.1.0
astropy @ git+https://github.com/astropy/astropy@f2fbb112983e953fb772c5ac81ec50dfa34bcc19
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.1.0
crds==11.17.0
execnet==1.9.0
filelock==3.12.0
idna==3.4
importlib-metadata==6.6.0
iniconfig==2.0.0
jmespath==1.0.1
jsonschema==4.17.3
numpy==1.25.0.dev0+1357.ga2d21d8ac
packaging==23.1
Parsley==1.3
pluggy==1.0.0
pyerfa==2.0.0.3
pyrsistent==0.19.3
pytest==7.3.1
pytest-doctestplus==0.12.1
pytest-xdist==3.2.1
PyYAML==6.0
requests==2.30.0
semantic-version==2.10.0
stpipe @ file:///Users/zburnett/projects/stpipe/.tox/.tmp/package/5/stpipe-0.5.1.dev3%2Bg643d3f9-py3-none-any.whl#sha256=f97ee1340df2f8016212619e8e96ae2c05c5a4832f04af861a2e7459f76ab0f9
urllib3==2.0.2
zipp==3.15.0
```

2023-06-05 12:57 UTC, zacharyburnett commented on tox.ini
> +    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/scipy-wheels-nightly/simple
```suggestion
    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
```

2023-07-24 11:25 UTC, merged